name: rudder_integration_appcenter_flutter
description: RudderStack's Flutter Implementation for Visual Studio App Center.
version: 1.0.0-beta1
author: Desu Sai Venkat 
homepage: https://github.com/rudderlabs/rudder-integration-appcenter-flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  rudder_sdk_flutter: ^1.0.1-beta1 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rudderstack.sdk.flutter.integrations.appcenter
        pluginClass: AppcenterPlugin
      ios:
        pluginClass: AppcenterPlugin
